spring:
  application:
    name: print-script-manager
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER}
  data:
    redis:
      host: redis
      port: 6379

stream:
  redis:
    stream:
      lint:
        key: ${STREAM_LINT_KEY}
      format:
        key: ${STREAM_FORMAT_KEY}
      status:
        key: ${STREAM_STATUS_KEY}
    consumer:
      group: ${STREAM_CONSUMER_GROUP_SNIPPET}

server:
  port: 8082

auth0:
  issuer: https://${AUTH_SERVER_URI}/
  audience: ${AUTH0_AUDIENCE}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      show-details: always