name: Publicar Imagen Docker

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build-and-push-to-ghcr:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

    permissions:
      contents: read
      packages: write # Permiso para publicar en GHCR

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Token automático de GitHub

      - name: Construir y publicar la imagen (CD)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ghcr.io/ingsis-second-chance/print-script-manager:${{ env.IMAGE_TAG }}
          file: ./Dockerfile
          secrets: |
            gpr_user=${{ github.actor }}
            gpr_token=${{ secrets.GITHUB_TOKEN }}

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push-to-ghcr

    env:
      SSH_KEY: ${{ github.ref_name == 'main' && secrets.SSH_KEY_PROD || secrets.SSH_KEY_DEV }}
      VM_NAME: ${{ github.ref_name == 'main' && 'vm-prod' || 'vm-dev' }}
      AZURE_RG: ${{ github.ref_name == 'main' && secrets.AZURE_RG_PROD || secrets.AZURE_RG_DEV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0 # Evita exponer la clave privada en los logs
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Start VM
        run: |
          az vm start --resource-group ${{ env.AZURE_RG }} --name ${{ env.VM_NAME }} --no-wait
          sleep 60 # Esperar un tiempo prudencial para que el SSH esté disponible
        shell: bash

      - name: Deploy to Azure VM (prod)
        if: github.ref_name == 'main'
        run: |
          ssh -v -o StrictHostKeyChecking=no ingsis@${{ secrets.VM_PROD_IP }} << ENDSSH
          cd infra
          docker compose -f docker-compose.prod.yml down print-script-manager
          docker compose -f docker-compose.prod.yml pull print-script-manager
          docker compose -f docker-compose.prod.yml up -d print-script-manager
          ENDSSH

      - name: Deploy to Azure VM (dev)
        if: github.ref_name != 'main'
        run: |
          ssh -v -o StrictHostKeyChecking=no ingsis@${{ secrets.VM_DEV_IP }} << ENDSSH
          cd infra
          docker compose -f docker-compose.dev.yml down print-script-manager
          docker compose -f docker-compose.dev.yml pull print-script-manager
          docker compose -f docker-compose.dev.yml up -d print-script-manager
          ENDSSH

      - name: Stop VM
        if: always() # Asegura que la VM se apague incluso si el despliegue falla
        run: |
          az vm stop --resource-group ${{ env.AZURE_RG }} --name ${{ env.VM_NAME }} --no-wait
        shell: bash