name: CI

on:
  push:
    branches: [ main, dev, "**/feature/**" ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: # para que gradle pueda acceder a los otros repos
      USERNAME: ${{ secrets.GPR_USER_SECRET }}
      TOKEN: ${{ secrets.GPR_KEY_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Spotless (formatter)
        run: ./gradlew spotlessCheck --no-daemon

      - name: Checkstyle (linter)
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon

      - name: Build & Test
        run: ./gradlew clean test --no-daemon